# Generated by Django 2.2.6 on 2021-10-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20210927_1526"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-pub_date"]},
        ),
    ]
